<?php
declare(strict_types = 1);

//
//  TagMapper.php
//  Cappuccino-Backend
//
//  Created by Claude and Alexandra Göttlicher
//

namespace Cappuccino\Service;

use Cappuccino\Entity\StationTag;

final readonly class TagMapper {
    private const array TAG_MAP = [
        // 50s
        '1950s' => '50s',
        'fifties' => '50s',
        "50's" => '50s',
        '50er' => '50s',
        'hits 50s' => '50s',
        "oldies 50's" => '50s',
        'oldies' => '50s',
        'golden oldies' => '50s',

        // 60s
        '1960s' => '60s',
        'sixties' => '60s',
        "60's" => '60s',
        '60er' => '60s',
        "hits 60's" => '60s',

        // 70s
        '1970s' => '70s',
        'seventies' => '70s',
        "70's" => '70s',
        '70er' => '70s',
        "hits 70's" => '70s',
        '70-е' => '70s',

        // 80s
        '1980s' => '80s',
        "1980's" => '80s',
        'eighties' => '80s',
        "80's" => '80s',
        '80er' => '80s',
        '80' => '80s',
        '80s radio' => '80s',
        '80s rock' => '80s',
        'all 80s' => '80s',
        'the best of 80s' => '80s',
        "the best of 80's" => '80s',
        'anos 80' => '80s',
        '80-е' => '80s',
        'хиты 80-х' => '80s',

        // 90s
        '1990s' => '90s',
        'nineties' => '90s',
        "90's" => '90s',
        '90er' => '90s',
        '90' => '90s',
        'classic 90s' => '90s',
        "hits 90's" => '90s',
        '90-е' => '90s',
        'хиты 90-х' => '90s',

        // 2000s
        '00s' => '2000s',
        "00's" => '2000s',
        '2000er' => '2000s',

        // 2010s
        '10s' => '2010s',
        '2010er' => '2010s',

        // Alternative
        'alternative rock' => 'alternative',
        'alternative wave' => 'alternative',
        'альтернатив' => 'alternative',
        'música alternativa' => 'alternative',

        // Ambient
        'dark ambient' => 'ambient',
        'space' => 'ambient',
        'atmospheric' => 'ambient',
        'new age' => 'ambient',
        'soundscape' => 'ambient',
        'sounds of nature' => 'ambient',
        'nature' => 'ambient',
        'sound of ocean' => 'ambient',
        'drone' => 'ambient',

        // Blues
        'blues rock' => 'blues',
        'blues music' => 'blues',
        'classic blues' => 'blues',
        'country blues' => 'blues',
        'блюз' => 'blues',

        // Chill
        'chillout' => 'chill',
        'chill out' => 'chill',
        'chillout radio' => 'chill',
        '#chillout' => 'chill',
        'chillout+lounge' => 'chill',
        'relaxing' => 'chill',
        'relaxation' => 'chill',
        'relaxation music' => 'chill',
        'relax' => 'chill',
        'calm' => 'chill',
        'zen' => 'chill',
        'yoga' => 'chill',
        'meditation' => 'chill',
        'easy listening' => 'chill',
        'chillwave' => 'chill',
        'chillsynth' => 'chill',
        'чилаут' => 'chill',
        'релакс' => 'chill',
        'расслабляющая' => 'chill',
        'méditation' => 'chill',

        // Classical
        'classical' => 'classic',
        'classical music' => 'classic',
        'classic music' => 'classic',
        'classique' => 'classic',
        'piano' => 'classic',
        'classical piano' => 'classic',
        'piano jazz' => 'classic',
        'opera' => 'classic',
        'symphony' => 'classic',
        'symphonic' => 'classic',
        'orchestra' => 'classic',
        'baroque' => 'classic',
        'chamber music' => 'classic',
        'choral' => 'classic',
        'choir' => 'classic',
        'neoclassical' => 'classic',
        'modern classical' => 'classic',
        'modern composition' => 'classic',
        'классика' => 'classic',
        'классическая музыка' => 'classic',
        'clásica' => 'classic',
        'música clásica' => 'classic',
        'guitarra clásica' => 'classic',
        'كلاسيك' => 'classic',
        'اغاني كلاسيكيه' => 'classic',
        'tarab' => 'classic',
        'طرب' => 'classic',

        // Country
        'country music' => 'country',
        'country rock' => 'country',
        'country pop' => 'country',
        'classic country' => 'country',
        'new country' => 'country',
        'traditional country' => 'country',
        'americana' => 'country',
        'nashville' => 'country',
        'alternative country' => 'country',
        'insurgent country' => 'country',

        // Culture
        'cultural' => 'culture',
        'cultura' => 'culture',
        'kultur' => 'culture',
        'cultural news' => 'culture',
        'educational' => 'culture',
        'multicultural' => 'culture',
        'multikulti' => 'culture',
        'arts' => 'culture',

        // Dance
        'club' => 'dance',
        'clubbing' => 'dance',
        'club dance' => 'dance',
        'club hits' => 'dance',
        'dancefloor' => 'dance',
        'party' => 'dance',
        'party hits' => 'dance',
        'partymix' => 'dance',
        'partyhits' => 'dance',
        'eurodance' => 'dance',
        'pop dance' => 'dance',
        'dance pop' => 'dance',
        'танцевальная' => 'dance',
        'танцевальная музыка' => 'dance',
        'клубная' => 'dance',
        'танцевальный' => 'dance',
        'música dance' => 'dance',

        // Disco
        'nu disco' => 'disco',
        'italo disco' => 'disco',
        'euro disco' => 'disco',
        'disco funk' => 'disco',
        'disco soul' => 'disco',
        'space disco' => 'disco',
        'rare disco' => 'disco',
        'диско' => 'disco',
        'music диско' => 'disco',

        // Downtempo
        'trip hop' => 'downtempo',
        'trip-hop' => 'downtempo',
        'downbeat' => 'downtempo',
        'broken beat' => 'downtempo',

        // Dubstep
        'chillstep' => 'dubstep',
        'post dubstep' => 'dubstep',
        'bass' => 'dubstep',
        'bass music' => 'dubstep',
        'future bass' => 'dubstep',
        'uk bass' => 'dubstep',

        // Electronic
        'electronic' => 'electronic',
        'electro' => 'electronic',
        'electronica' => 'electronic',
        'edm' => 'electronic',
        'electronic dance music' => 'electronic',
        'electronic beats' => 'electronic',
        'elektro' => 'electronic',
        'elektronik' => 'electronic',
        'idm' => 'electronic',
        'glitch' => 'electronic',
        'experimental' => 'electronic',
        'avant-garde' => 'electronic',
        'avantgarde' => 'electronic',
        'электронная' => 'electronic',
        'электронная музыка' => 'electronic',
        'электроника' => 'electronic',
        'eletrônica' => 'electronic',
        'música electrónica' => 'electronic',

        // Entertainment
        'talk' => 'entertainment',
        'talk radio' => 'entertainment',
        'talk show' => 'entertainment',
        'talk show radio' => 'entertainment',
        'comedy' => 'entertainment',
        'variety' => 'entertainment',
        'variety hits' => 'entertainment',
        'variedades' => 'entertainment',
        'entretenimiento' => 'entertainment',
        'юмор' => 'entertainment',
        'разговорное' => 'entertainment',
        'разговорный' => 'entertainment',

        // Folk
        'folk rock' => 'folk',
        'folk music' => 'folk',
        'classic folk' => 'folk',
        'progressive folk' => 'folk',
        'acoustic' => 'folk',
        'acoustic guitar' => 'folk',
        'singer-songwriter' => 'folk',
        'celtic' => 'folk',
        'world music' => 'folk',
        'world' => 'folk',
        'worldbeat' => 'folk',
        'traditional' => 'folk',
        'folklore' => 'folk',
        'ethnic' => 'folk',
        'arabesk' => 'folk',
        'arabesk fantazi' => 'folk',
        'arabic music' => 'folk',
        'arab music' => 'folk',
        'arabic' => 'folk',
        'arab' => 'folk',
        'arabic hits' => 'folk',
        'arabic songs' => 'folk',
        'music arabe' => 'folk',
        'الموسيقى العربية' => 'folk',
        'عربي' => 'folk',
        'фолк' => 'folk',
        'этно' => 'folk',
        'фолк-рок' => 'folk',
        'фолклор' => 'folk',
        'народна' => 'folk',
        'народне' => 'folk',

        // Funk
        'funky' => 'funk',
        'electro funk' => 'funk',
        'jazz funk' => 'funk',
        'future funk' => 'funk',
        'фанк' => 'funk',

        // Groove
        'rare groove' => 'groove',
        'nu grooves' => 'groove',

        // Hard Rock
        'hardrock' => 'hard rock',
        'heavy rock' => 'hard rock',
        'melodic rock' => 'hard rock',
        'melodic hard rock' => 'hard rock',
        'aor' => 'hard rock',

        // Hits
        'top 40' => 'hits',
        'top40' => 'hits',
        'top 100' => 'hits',
        'top hits' => 'hits',
        'top charts' => 'hits',
        'charts' => 'hits',
        '#charts' => 'hits',
        'hot hits' => 'hits',
        'hot' => 'hits',
        'greatest hits' => 'hits',
        'classic hits' => 'hits',
        'adult hits' => 'hits',
        'contemporary hits' => 'hits',
        'latest hits' => 'hits',
        'hit' => 'hits',
        'workout' => 'hits',
        'gym' => 'hits',
        'fitness' => 'hits',
        'fitness music' => 'hits',
        'running' => 'hits',
        'mainstream' => 'hits',
        'хиты' => 'hits',
        'хит fm' => 'hits',
        'хиты прошлых лет' => 'hits',
        'éxitos' => 'hits',
        'variado' => 'hits',

        // House
        'deep house' => 'house',
        'tech house' => 'house',
        'progressive house' => 'house',
        'melodic house' => 'house',
        'club house' => 'house',
        'soulful house' => 'house',
        'funky house' => 'house',
        'future house' => 'house',
        'bass house' => 'house',
        'organic house' => 'house',
        'acid-house' => 'house',
        'acid house' => 'house',
        'balearic house' => 'house',
        'ibiza' => 'house',
        'ibiza club' => 'house',
        'дип хаус' => 'house',

        // Indie
        'indie rock' => 'indie',
        'indie music' => 'indie',
        'indie pop' => 'indie',
        'independent' => 'indie',
        'independent music' => 'indie',
        'инди' => 'indie',
        'инди-рок' => 'indie',

        // Jazz
        'smooth jazz' => 'jazz',
        'latin jazz' => 'jazz',
        'classic jazz' => 'jazz',
        'contemporary jazz' => 'jazz',
        'nu-jazz' => 'jazz',
        'nu jazz' => 'jazz',
        'acid jazz' => 'jazz',
        'free jazz' => 'jazz',
        'cool jazz' => 'jazz',
        'vocal jazz' => 'jazz',
        'guitar jazz' => 'jazz',
        'bebop' => 'jazz',
        'hard bop' => 'jazz',
        'post-bop' => 'jazz',
        'swing' => 'jazz',
        'big band' => 'jazz',
        'big bands' => 'jazz',
        'dixieland' => 'jazz',
        'fusion' => 'jazz',
        'jazz fusion' => 'jazz',
        'jazz rock' => 'jazz',
        'jazz-rock' => 'jazz',
        'jazz music' => 'jazz',
        'jazz lounge' => 'jazz',
        'jazzy' => 'jazz',
        'джаз' => 'jazz',

        // Kpop
        'korean pop' => 'kpop',
        'k-pop' => 'kpop',
        'jpop' => 'kpop',
        'j-pop' => 'kpop',

        // Latin
        'latin music' => 'latin',
        'latin pop' => 'latin',
        'latino' => 'latin',
        'latino-pop' => 'latin',
        'pop latino' => 'latin',
        'musica latina' => 'latin',
        'música latina' => 'latin',
        'salsa' => 'latin',
        'bachata' => 'latin',
        'merengue' => 'latin',
        'cumbia' => 'latin',
        'reggaeton' => 'latin',
        'tropical' => 'latin',
        'musica tropical' => 'latin',
        'bossa nova' => 'latin',
        'bossanova' => 'latin',
        'bossa' => 'latin',
        'brazilian' => 'latin',
        'brazilian music' => 'latin',
        'brasil' => 'latin',
        'brazil' => 'latin',
        'mpb' => 'latin',
        'música popular brasileira' => 'latin',
        'forró' => 'latin',
        'sertanejo' => 'latin',
        'sertaneja' => 'latin',
        'axé' => 'latin',
        'tango' => 'latin',
        'tango nuevo' => 'latin',
        'mexican music' => 'latin',
        'música mexicana' => 'latin',
        'regional mexicana' => 'latin',
        'regional mexican' => 'latin',
        'música regional mexicana' => 'latin',
        'música en español' => 'latin',
        'spanish hits' => 'latin',
        'latinoamérica' => 'latin',
        'latinoamerica' => 'latin',

        // Lounge
        'lounge music' => 'lounge',
        'lounge radio' => 'lounge',
        'smooth lounge' => 'lounge',
        'cafe' => 'lounge',
        'cocktail' => 'lounge',
        'lofi' => 'lounge',
        'lo-fi' => 'lounge',
        'лаундж' => 'lounge',

        // Metal
        'heavy metal' => 'metal',
        'death metal' => 'metal',
        'black metal' => 'metal',
        'thrash metal' => 'metal',
        'doom metal' => 'metal',
        'power metal' => 'metal',
        'symphonic metal' => 'metal',
        'gothic metal' => 'metal',
        'melodic metal' => 'metal',
        'melodic heavy metal' => 'metal',
        'nu metal' => 'metal',
        'metalcore' => 'metal',
        'progressive metal' => 'metal',
        'folk metal' => 'metal',
        'pagan metal' => 'metal',
        'brutal death metal' => 'metal',
        'symphonic death metal' => 'metal',
        'epic metal' => 'metal',
        'металл' => 'metal',

        // News
        'news talk' => 'news',
        'world news' => 'news',
        'local news' => 'news',
        'information' => 'news',
        'current affairs' => 'news',
        'journalism' => 'news',
        'npr' => 'news',
        'public radio' => 'news',
        'новости' => 'news',
        'местные новости' => 'news',
        'информационный' => 'news',
        'информационное' => 'news',
        'noticias' => 'news',
        'notícias' => 'news',
        'jornalismo' => 'news',
        'الجزيرة' => 'news',
        'قناة الجزيرة' => 'news',

        // Phonk
        'drift phonk' => 'phonk',

        // Pop
        'pop music' => 'pop',
        'pop rock' => 'pop',
        'pop-rock' => 'pop',
        'poprock' => 'pop',
        'soft pop' => 'pop',
        'german pop' => 'pop',
        'turkish pop' => 'pop',
        'dutch pop' => 'pop',
        'greek pop' => 'pop',
        'adult contemporary' => 'pop',
        'soft adult contemporary' => 'pop',
        'hot adult contemporary' => 'pop',
        'contemporary' => 'pop',
        'electropop' => 'pop',
        'synthpop' => 'pop',
        'synth-pop' => 'pop',
        'поп' => 'pop',
        'поп-музыка' => 'pop',
        'популярная музыка' => 'pop',
        'русская популярная музыка' => 'pop',
        'современная музыка' => 'pop',
        'música pop' => 'pop',
        'поп-рок' => 'pop',
        'софт-рок' => 'pop',
        'romántica' => 'pop',
        'música romántica' => 'pop',
        'balada romántica' => 'pop',
        'musica romántica' => 'pop',
        'românticas' => 'pop',

        // Progressive
        'progressive rock' => 'progressive',
        'prog rock' => 'progressive',
        'progressive trance' => 'progressive',
        'neo-progressive rock' => 'progressive',
        'crossover prog' => 'progressive',
        'art rock' => 'progressive',
        'symphonic rock' => 'progressive',
        'post rock' => 'progressive',
        'post-rock' => 'progressive',
        'math rock' => 'progressive',

        // Rap
        'hip hop' => 'rap',
        'hip-hop' => 'rap',
        'hiphop' => 'rap',
        'rnb' => 'rap',
        'r&b' => 'rap',
        "r'n'b" => 'rap',
        'r n b' => 'rap',
        'rhythm and blues' => 'rap',
        'urban' => 'rap',
        'urban music' => 'rap',
        'black music' => 'rap',
        'trap' => 'rap',
        'gangsta rap' => 'rap',
        'east coast rap' => 'rap',
        'old school hip hop' => 'rap',
        'german rap' => 'rap',
        'german hip-hop' => 'rap',
        'dutch rap' => 'rap',
        'dutch hip hop' => 'rap',
        'usrap' => 'rap',
        '#usrap' => 'rap',
        'grime' => 'rap',
        'cloud rap' => 'rap',
        'hardcore rap' => 'rap',
        'хип-хоп' => 'rap',
        'рэп' => 'rap',

        // Reggae
        'roots reggae' => 'reggae',
        'smooth reggae' => 'reggae',
        'dub' => 'reggae',
        'dancehall' => 'reggae',
        'ska' => 'reggae',
        'ska punk' => 'reggae',
        'реггей' => 'reggae',

        // Religious
        'christian' => 'religious',
        'catholic' => 'religious',
        'worship' => 'religious',
        'gospel' => 'religious',
        'prayer' => 'religious',
        'orthodox' => 'religious',
        'buddhism' => 'religious',
        'islamic' => 'religious',
        'devotional' => 'religious',
        'spiritual' => 'religious',
        'christian contemporary' => 'religious',
        'contemporary christian' => 'religious',
        'christian talk' => 'religious',
        'christian-gospel' => 'religious',
        'praise' => 'religious',
        'praise and worship' => 'religious',
        'religion' => 'religious',
        'religia' => 'religious',
        'christlich' => 'religious',
        'católica' => 'religious',
        'cristiana' => 'religious',
        'cristiano' => 'religious',
        'cristã' => 'religious',
        'sacred' => 'religious',
        'liturgical' => 'religious',
        'gospel evangélica' => 'religious',
        'evangélica' => 'religious',
        'música cristiana' => 'religious',
        'musica cristiana' => 'religious',
        'radio cristiana' => 'religious',
        'música religiosa' => 'religious',
        'православие' => 'religious',
        'християнство' => 'religious',
        'القرآن الكريم' => 'religious',
        'القرآن' => 'religious',
        'راديو القرآن' => 'religious',
        'قران كريم' => 'religious',
        'قران' => 'religious',
        'اسلامي' => 'religious',
        'اسلام' => 'religious',
        'دين' => 'religious',
        'مسلم' => 'religious',
        'مشاري العفاسي' => 'religious',
        'ياسر الدوسري' => 'religious',
        'علي الحذيفي' => 'religious',
        'ماهر المعيقلي' => 'religious',
        'السديس' => 'religious',
        'عبدالرحمن' => 'religious',
        'عبدالباسط' => 'religious',
        'عبدالصمد' => 'religious',
        'سعود الشريم' => 'religious',

        // Rock
        'classic rock' => 'rock',
        'rock-classic' => 'rock',
        'classic rock music' => 'rock',
        'rock n roll' => 'rock',
        'rock and roll' => 'rock',
        "rock'n'roll" => 'rock',
        'guitar rock' => 'rock',
        'southern rock' => 'rock',
        'psychedelic rock' => 'rock',
        'stoner rock' => 'rock',
        'space rock' => 'rock',
        'surf rock' => 'rock',
        'rockabilly' => 'rock',
        'grunge' => 'rock',
        'post grunge' => 'rock',
        'punk' => 'rock',
        'punk rock' => 'rock',
        '90s alternative' => 'rock',
        'britpop' => 'rock',
        'brit pop' => 'rock',
        'modern rock' => 'rock',
        'soft rock' => 'rock',
        'gothic' => '80s',
        'gothic rock' => '80s',
        'рок' => 'rock',
        'русский рок' => 'rock',
        'панк' => 'rock',

        // Schlager
        'schlageroldies' => 'schlager',
        'schlagerhits' => 'schlager',
        'volksmusik' => 'schlager',
        'volkstümlicher schlager' => 'schlager',
        'discofox+schlager' => 'schlager',
        'discofox' => 'schlager',
        'шансон' => 'schlager',
        'русский шансон' => 'schlager',
        'music шансон' => 'schlager',

        // Sleep
        'sleeping' => 'sleep',
        'sleep music' => 'sleep',

        // Soul
        'soulful' => 'soul',
        'neo soul' => 'soul',
        'classic soul' => 'soul',
        'motown' => 'soul',
        'afro soul' => 'soul',
        'afrosoul' => 'soul',
        'pop soul' => 'soul',
        'northern soul' => 'soul',
        'соул' => 'soul',

        // Sports
        'sport' => 'sports',
        'sports news' => 'sports',
        'sports talk' => 'sports',
        'live sports' => 'sports',
        'football' => 'sports',
        'football commentary' => 'sports',
        'futbol' => 'sports',
        'futebol' => 'sports',
        'esportes' => 'sports',
        'deportes' => 'sports',
        'спорт' => 'sports',

        // Storytelling
        'old time radio' => 'storytelling',
        'audiobook' => 'storytelling',
        'audiobooks' => 'storytelling',
        'drama' => 'storytelling',
        'spoken word' => 'storytelling',
        'podcast' => 'storytelling',
        'otr' => 'storytelling',
        'аудиокниги' => 'storytelling',
        'рассказы' => 'storytelling',
        'фантастика' => 'storytelling',
        'литература' => 'storytelling',

        // Techno
        'minimal techno' => 'techno',
        'dark techno' => 'techno',
        'dub techno' => 'techno',
        'hardtechno' => 'techno',
        'schranz' => 'techno',
        'industrial' => 'techno',
        'ebm' => 'techno',
        'hardcore' => 'techno',
        'hardstyle' => 'techno',
        'hard dance' => 'techno',
        'hardbass' => 'techno',
        'gabber' => 'techno',
        'rave' => 'techno',
        'minimal' => 'techno',
        'acid' => 'techno',
        'acid techno' => 'techno',
        'drum and bass' => 'techno',
        'drum n bass' => 'techno',
        "drum 'n' bass" => 'techno',
        'drum&bass' => 'techno',
        'dnb' => 'techno',
        'jungle' => 'techno',
        'liquid funk' => 'techno',
        'liquid dnb' => 'techno',
        'neurofunk' => 'techno',
        'breakbeat' => 'techno',
        'breaks' => 'techno',
        'big beat' => 'techno',

        // Trance
        'psytrance' => 'trance',
        'goa' => 'trance',
        'goa trance' => 'trance',
        'progressive trance' => 'trance',
        'uplifting trance' => 'trance',
        'trance uplifting' => 'trance',
        'vocal trance' => 'trance',

        // Retro
        'vintage' => 'retro',
        'vintage music' => 'retro',
        'retro' => 'retro',
        'retrô' => 'retro',
        'nostalgia' => 'retro',
        'nostalgie' => 'retro',
        'golden' => 'retro',
        'goldies' => 'retro',
        'classics' => 'retro',
        'ретро' => 'retro',

        // Wave
        'synthwave' => 'wave',
        'retrowave' => 'wave',
        'outrun' => 'wave',
        'darksynth' => 'wave',
        'new wave' => 'wave',
        'new-wave' => 'wave',
        'post-punk' => 'wave',
        'darkwave' => 'wave',

        // MISCELLANEOUS RUSSIAN
        'музыка' => 'hits',
        'разная музыка' => 'hits',
        'лëгкая музыка' => 'lounge',
        'лëгкая' => 'lounge',
        'романтическая' => 'pop',
        'бард' => 'folk',
        'авторская песня' => 'folk',
        'бард-рок' => 'folk',
        'романс' => 'classic',
        'советская эстрада' => 'classic',
        'каверы' => 'hits',
        'политика' => 'news',
        'наука' => 'culture',
        'научно-познавательное' => 'culture',
        'кино' => 'entertainment',

        // MISCELLANEOUS PERSIAN/FARSI
        'رادیو' => 'entertainment',
        'فارسی' => 'folk',
    ];

    public function map(string $rawTag): ?string {
        // Direct match with allowed tags
        if (in_array(needle: $rawTag, haystack: StationTag::ALLOWED_TAGS, strict: true)) {
            return $rawTag;
        }

        // Check explicit mapping
        if (isset(self::TAG_MAP[$rawTag])) {
            return self::TAG_MAP[$rawTag];
        }

        // Fallback: check if the tag contains an allowed tag as a word boundary
        foreach (StationTag::ALLOWED_TAGS as $allowedTag) {
            if (preg_match(pattern: '/\b' . preg_quote(str: $allowedTag, delimiter: '/') . '\b/u', subject: $rawTag)) {
                return $allowedTag;
            }
        }

        return null;
    }

    public function mapMany(array $rawTags): array {
        $mappedTags = [];

        foreach ($rawTags as $rawTag) {
            $mapped = $this->map(rawTag: $rawTag);
            if ($mapped) {
                $mappedTags[$mapped] = true;
            }
        }

        return array_keys(array: $mappedTags);
    }
}
