<?php
declare(strict_types = 1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260205214000 extends AbstractMigration {
    /**
     * @return string
     */
    public function getDescription(): string {
        return 'Creates the initial database schema.';
    }

    /**
     * @param Schema $schema
     */
    public function up(Schema $schema): void {
        $this->addSql('CREATE TABLE station_countries (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, iso_3166_2 VARCHAR(2) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DFE285B6C5FD59E4 ON station_countries (iso_3166_2)');
        $this->addSql('CREATE TABLE station_languages (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, iso_639_1 VARCHAR(2) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_22553D623F88B6DB ON station_languages (iso_639_1)');
        $this->addSql('CREATE TABLE station_tags (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(16) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_818FB31B5E237E06 ON station_tags (name)');
        $this->addSql('CREATE TABLE stations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, name VARCHAR(32) NOT NULL, stream_url VARCHAR(256) NOT NULL, homepage_url VARCHAR(128) DEFAULT NULL, icon_url VARCHAR(256) DEFAULT NULL, station_country_id SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A7F775E9D17F50A6 ON stations (uuid)');
        $this->addSql('CREATE INDEX IDX_A7F775E973C873F2 ON stations (station_country_id)');
        $this->addSql('CREATE TABLE station_station_language (station_id INT NOT NULL, station_language_id SMALLINT NOT NULL, PRIMARY KEY (station_id, station_language_id))');
        $this->addSql('CREATE INDEX IDX_C50651F21BDB235 ON station_station_language (station_id)');
        $this->addSql('CREATE INDEX IDX_C50651F81CDBFB5 ON station_station_language (station_language_id)');
        $this->addSql('CREATE TABLE station_station_tag (station_id INT NOT NULL, station_tag_id SMALLINT NOT NULL, PRIMARY KEY (station_id, station_tag_id))');
        $this->addSql('CREATE INDEX IDX_3DF3A3C021BDB235 ON station_station_tag (station_id)');
        $this->addSql('CREATE INDEX IDX_3DF3A3C0753070F7 ON station_station_tag (station_tag_id)');
        $this->addSql('ALTER TABLE stations ADD CONSTRAINT FK_A7F775E973C873F2 FOREIGN KEY (station_country_id) REFERENCES station_countries (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE station_station_language ADD CONSTRAINT FK_C50651F21BDB235 FOREIGN KEY (station_id) REFERENCES stations (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE station_station_language ADD CONSTRAINT FK_C50651F81CDBFB5 FOREIGN KEY (station_language_id) REFERENCES station_languages (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE station_station_tag ADD CONSTRAINT FK_3DF3A3C021BDB235 FOREIGN KEY (station_id) REFERENCES stations (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE station_station_tag ADD CONSTRAINT FK_3DF3A3C0753070F7 FOREIGN KEY (station_tag_id) REFERENCES station_tags (id) ON DELETE CASCADE');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema): void {
        $this->addSql('ALTER TABLE stations DROP CONSTRAINT FK_A7F775E973C873F2');
        $this->addSql('ALTER TABLE station_station_language DROP CONSTRAINT FK_C50651F21BDB235');
        $this->addSql('ALTER TABLE station_station_language DROP CONSTRAINT FK_C50651F81CDBFB5');
        $this->addSql('ALTER TABLE station_station_tag DROP CONSTRAINT FK_3DF3A3C021BDB235');
        $this->addSql('ALTER TABLE station_station_tag DROP CONSTRAINT FK_3DF3A3C0753070F7');
        $this->addSql('DROP TABLE station_countries');
        $this->addSql('DROP TABLE station_languages');
        $this->addSql('DROP TABLE station_tags');
        $this->addSql('DROP TABLE stations');
        $this->addSql('DROP TABLE station_station_language');
        $this->addSql('DROP TABLE station_station_tag');
    }
}
